<?php
/***********************************************************************************
 * The content of this file is subject to the ITS4YouPicklistImport license.
 * ("License"); You may not use this file except in compliance with the License
 * The Initial Developer of the Original Code is IT-Solutions4You s.r.o.
 * Portions created by IT-Solutions4You s.r.o. are Copyright(C) IT-Solutions4You s.r.o.
 * All Rights Reserved.
 ************************************************************************************/

class ITS4YouPicklistImport_Module_Model extends Vtiger_Module_Model {

	public function isExportable() {
        return false;
    }

    public function getDefaultUrl() {
	    return 'index.php?parent=Settings&module=Picklist&view=Index'; // TODO: Change the autogenerated stub
    }
}
